apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruits-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruits
  template:
    metadata:
      labels:
        app: fruits
    spec:
      containers:
        - name: database
          image: mcr.microsoft.com/mssql/server:2019-latest
          env:
            - name: MSSQL_SA_PASSWORD
              value: Root@2024
            - name: ACCEPT_EULA
              value: 'Y'
        
        - name: fruits
          image: ndambuki/kub-networking-demo
       
     