apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-object
spec:
  replicas: 2
  selector:
    matchLabels:
      app: volumes
  template:
    metadata:
      labels:
        app: volumes
    spec:
      containers:
        - name: volumes-container
          image: ndambuki/kub-volume-demo
          volumeMounts:
            - mountPath: /app/students
              name: student-volume
      volumes:
        - name: student-volume
          emptyDir: {}

