apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: students-pvc
spec:
  volumeName: students-pv
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
